### ISSUE TITLE
Search: Pagination

### ISSUE THREAD

**Issue by Zygmut** [Zygmut/Majorcan_beaches#55]

**Comment by Bloneon** [comment]
## Backlog functionalities
- [ ] Arrow buttons, change state of button that indicates actual page
- [ ] Boundaries issues:
  - [ ] Right boundary, when used right button, it should slide all buttons content (number) 1 position to the right.
  - [ ] Left boundary, when used left button, if the first button is not the first page (number distinct to "1") it should slide all buttons one position to the left.
  
- [ ] When right button is used, afterward it should become unchecked again.
